### ISSUE TITLE
ER: To add more options for charting 

### ISSUE THREAD

**Issue by anjuls** [ppalucha/spa#1]
Hi,

It is wonderful tool. Sometimes it fails parsing AWR with error but I think that depends which Tool has generated the AWR (for. e.g. Toad). Is it possible to plot charts only by selecting the database for all instances. As of now, we need to select individual instances to see the charts. If such option for all instances possible, then it would be great. Also for one host, all databases (may help in capacity planning). 

Thanks
Anjul

**Comment by ppalucha** [comment]
Hi,
Sometimes the AWR reports are not properly formatted HTML files - so they will fail to parse unless you fix them manually (for example remove superfluous spaces). But if you have some other examples of non-parsing reports, you can send them and I will check if parser can be improved.
As for summary charts for databases I could think of it. However, it will not make sense for all the charts.
And I'm not really sure about the summary for hosts - different databases will not have many common characteristics.
Regards
Pawel

**Comment by anjuls** [comment]
Ok,  i will let you know the exact error when it happens next.  Thanks.
