### ISSUE TITLE
Charts are not rendering

### ISSUE THREAD

**Issue by codeslord** [ppalucha/spa#2]
Everything is working for me except the charts. They are not rendering. Can you help me with this?

**Comment by ppalucha** [comment]
Not really - at least not with the level of details you provided ;-)

**Comment by codeslord** [comment]
I am getting the application open. But the charts are not rendering. I don't know whether this issue is with c3js. I am using the latest version of c3 and d3. I have tried both chrome and mozilla suspecting it as a browser issue. But still it is not getting rendered.

![screenshot from 2016-11-29 15-45-03](https://cloud.githubusercontent.com/assets/4618356/20705918/ec16e59c-b64a-11e6-82d6-c36bac967cf1.png)
Please let me know if you require any further information.

**Comment by ppalucha** [comment]
How many AWR files do you have loaded for this Data Set? It looks for me like you have only 1 file loaded. Therefore there will be only one data point and no charts are drawn. You need to load at least 2 AWR files (and preferably multiple) to get anything useful. With one file you can only hover mouse over data point, it should display values.

**Comment by codeslord** [comment]
okay, thanks for the update. let me check and update you shortly.

**Comment by codeslord** [comment]
It is working, thanks a lot.
